AWSTemplateFormatVersion: "2010-09-09"
Description: lambda-docker-puppeteer

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda-docker-puppeteer-sls
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  OutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda-docker-puppeteer-out
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpirationOut
            Status: Enabled
            Prefix: /
            ExpirationInDays: 1
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-docker-puppeteer-repos
